license_key: ''
bot_token: ''
client_id: ''
client_secret: ''
redirect_url: 'http://localhost:8080'
webhook_url: ''
owners:
  - '1180995483997569028'
  - '' # Leave blank if there are no other owners
  - '' # Leave blank if there are no other owners
embed_color: '6c02ff'
status:
  type: 'watching'  # Options: "playing", "watching", "listening", "competing"
  message: 'Moonly'
